### ISSUE TITLE
[Suggestion] Add body classes based on which page the user is on

### ISSUE THREAD

**Issue by heismauri** [coppermine-gallery/cpg1.6.x#48]
It would be a great feature to include body classes to enhance the personalization without modifying to much the main theme, just using css.

**Comment by ron4mac** [comment]
Since the `<body>` tag exists in the _<theme>/template.html_ file, accomplishing this would require some hacks.

The _theme.php_ file could define **THEME_WANTS_BODY_CLASS**.
In the _template.html_ file the body tag would be written as `<body class="{BODY_CLASS}">`
Whenever _pageheader()_ is bing called, it would have to do a backtrace to determine where it is being called from. It would use that information to form a body class name based on the page.

Do you have some idea for a different method (without completely re-writing CPG)?

**Comment by heismauri** [comment]
It can be an optional tag, like a user in the forum did [here](https://forum.coppermine-gallery.net/index.php/topic,79980.0.html)

**Comment by ron4mac** [comment]
That method is much too complicated and would run for all themes. And there is no reason for a body id if there is a class.

My (tested) code stuck in at the bottom of _pageheader()_:
```
if (defined('THEME_WANTS_BODY_CLASS')) {
	$bt = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS,3);
	$bc = 'BC'.basename(end($bt)['file'],'.php');
	$template_vars['{BODY_CLASS}'] = $bc;
}
```
So the home page body class would be: class="BCindex".
The 'BC' prefix is to avoid clashes.
And any theme will just need the two items I mentioned above.

**Comment by heismauri** [comment]
so that's a no, or a maybe? haha

**Comment by ron4mac** [comment]
Implemented the feature as described above.
